Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	covert_snps_table
	1	nonsyn_snps_table
	1	syn_snps_table
	4

[Tue Aug 21 18:23:26 2018]
rule nonsyn_snps_table:
    input: tmp/DNA_Pool1_final.tab, /net/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v5/data/reference/RefCln_UCBPP-PA14.gbk
    output: tmp/non-syn_SNPs.tab
    jobid: 2

    [Tue Aug 21 18:23:37 2018]
    Error in rule nonsyn_snps_table:
        jobid: 2
        output: tmp/non-syn_SNPs.tab

RuleException:
CalledProcessError in line 46 of /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v5/CREATE_SNPS_TABLE.smk:
Command ' set -euo pipefail;  
        source activate py27
        python snps_original_methods/Snp2Amino.edit.py -f tmp/DNA_Pool1_final.tab -g /net/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v5/data/reference/RefCln_UCBPP-PA14.gbk         -n non-syn         -o tmp/non-syn_SNPs.tab 
        source deactivate ' returned non-zero exit status 1.
  File "/net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v5/CREATE_SNPS_TABLE.smk", line 46, in __rule_nonsyn_snps_table
  File "/home/thkuo/miniconda3/envs/seq2geno/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v5/.snakemake/log/2018-08-21T182320.321452.snakemake.log
