Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	all_snps_list
	1	covert_snps_table
	1	create_dict_file
	1	nonsyn_snps_table
	1	syn_snps_table
	6

[Tue Aug 21 16:40:55 2018]
rule create_dict_file:
    input: CH2500.flt.vcf, CH2502.flt.vcf, CH2522.flt.vcf, F1659.flt.vcf
    output: dict.txt
    jobid: 13

[Tue Aug 21 16:40:55 2018]
Finished job 13.
1 of 6 steps (17%) done

[Tue Aug 21 16:40:55 2018]
rule all_snps_list:
    input: tmp/CH2500/bwa/st_variant.flatcount, tmp/CH2502/bwa/st_variant.flatcount, tmp/CH2522/bwa/st_variant.flatcount, tmp/F1659/bwa/st_variant.flatcount, CH2500.flt.vcf, CH2502.flt.vcf, CH2522.flt.vcf, F1659.flt.vcf, dict.txt, Pseudomonas_aeruginosa_PA14_annotation_with_ncRNAs_07_2011_12genes.tab
    output: /DNA_Pool1_final.tab
    jobid: 4

    [Tue Aug 21 16:40:59 2018]
    Error in rule all_snps_list:
        jobid: 4
        output: /DNA_Pool1_final.tab

RuleException:
CalledProcessError in line 113 of /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v5/CREATE_SNPS_TABLE.smk:
Command ' set -euo pipefail;  
        source activate py27
        python snps_original_methods/mutation_table.py  -f dict.txt         -a Pseudomonas_aeruginosa_PA14_annotation_with_ncRNAs_07_2011_12genes.tab         -o /DNA_Pool1_final.tab
        source deactivate ' returned non-zero exit status 1.
  File "/net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v5/CREATE_SNPS_TABLE.smk", line 113, in __rule_all_snps_list
  File "/home/thkuo/miniconda3/envs/seq2geno/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v5/.snakemake/log/2018-08-21T164050.502030.snakemake.log
