Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	aln_to_vcf
	1	sort_gene_family
	3

rule sort_gene_family:
    input: tmp/roary/gene_presence_absence.csv, tmp/prokka/CH2500/CH2500.ffn, tmp/prokka/CH2502/CH2502.ffn, tmp/prokka/CH2522/CH2522.ffn, tmp/prokka/F1659/F1659.ffn
    output: tmp/aln.list
    jobid: 2
    wildcards: TMP_D=tmp

Finished job 2.
1 of 3 steps (33%) done

rule aln_to_vcf:
    input: tmp/aln.list
    output: tmp/aln_vcf.list
    jobid: 1
    wildcards: TMP_D=tmp

    Error in rule aln_to_vcf:
        jobid: 1
        output: tmp/aln_vcf.list

RuleException:
CalledProcessError in line 112 of /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/CREATE_INDEL_TABLE.smk:
Command ' set -euo pipefail;  parallel -j 16 'java -jar jvarkit/dist/msa2vcf.jar< {}.aln > {}.vcf' ::: `cat tmp/aln.list | sed 's/\.aln$//'`;cat tmp/aln.list | sed 's/\.aln$/.vcf/' ' returned non-zero exit status 2.
  File "/net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/CREATE_INDEL_TABLE.smk", line 112, in __rule_aln_to_vcf
  File "/home/thkuo/miniconda3/envs/phypal/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /net/sgi/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v3/.snakemake/log/2018-07-15T211259.505680.snakemake.log
